version: '3.8'

services:
  db:
    image: ghcr.io/pgmq/pg17-pgmq:v1.5.1
    container_name: pgmq-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/postgres?search_path=pgmq,public&sslmode=disable
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
